# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kitchen.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'kitchen.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rkitchen.proto\x12\x07kitchen\"6\n\x08MenuItem\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\"_\n\x13ProcessOrderRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x14\n\x0ctable_number\x18\x02 \x01(\t\x12 \n\x05items\x18\x03 \x03(\x0b\x32\x11.kitchen.MenuItem\"P\n\x14ProcessOrderResponse\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x16\n\x0e\x65stimated_time\x18\x03 \x01(\x05\"<\n\x18UpdateOrderStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"=\n\x19UpdateOrderStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xbd\x01\n\x0eKitchenService\x12M\n\x0cProcessOrder\x12\x1c.kitchen.ProcessOrderRequest\x1a\x1d.kitchen.ProcessOrderResponse\"\x00\x12\\\n\x11UpdateOrderStatus\x12!.kitchen.UpdateOrderStatusRequest\x1a\".kitchen.UpdateOrderStatusResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kitchen_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MENUITEM']._serialized_start=26
  _globals['_MENUITEM']._serialized_end=80
  _globals['_PROCESSORDERREQUEST']._serialized_start=82
  _globals['_PROCESSORDERREQUEST']._serialized_end=177
  _globals['_PROCESSORDERRESPONSE']._serialized_start=179
  _globals['_PROCESSORDERRESPONSE']._serialized_end=259
  _globals['_UPDATEORDERSTATUSREQUEST']._serialized_start=261
  _globals['_UPDATEORDERSTATUSREQUEST']._serialized_end=321
  _globals['_UPDATEORDERSTATUSRESPONSE']._serialized_start=323
  _globals['_UPDATEORDERSTATUSRESPONSE']._serialized_end=384
  _globals['_KITCHENSERVICE']._serialized_start=387
  _globals['_KITCHENSERVICE']._serialized_end=576
# @@protoc_insertion_point(module_scope)
